name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: toru-oizumi
          template: classic
          config_timezone: Asia/Tokyo
          
          base: header, repositories
          repositories_batch: 100
          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 0 
          plugin_languages_recent_load: 1000

          plugin_lines: yes
          
          plugin_repositories: yes
          plugin_repositories_featured: toru-oizumi/slack-timeline-retro
